import { PagoAplicacionLineaDto } from './PagoAplicacionLineaDto';

export class PagoClienteDetalleDto {
  nId?: number;
  nIdCliente?: number;
  nIdDatoFactura?: number;
  fechaRegistro?: Date;
  fechaPago?: Date;
  importeTotal?: number;
  importeAplicado?: number;
  importeDisponible?: number;
  moneda?: string;
  nIdFormaPago?: number;
  formaPagoSat?: string;
  descripcionFormaPago?: string;
  referencia?: string;
  numeroAutorizacion?: string;
  folioOperacion?: string;
  claveRastreo?: string;
  bancoOrigen?: string;
  cuentaOrigen?: string;
  ultimos4CuentaOrigen?: string;
  bancoDestino?: string;
  cuentaDestino?: string;
  ultimos4CuentaDestino?: string;
  titularCuenta?: string;
  terminal?: string;
  numeroVoucher?: string;
  ultimos4Tarjeta?: string;
  tipoTarjeta?: string;
  redTarjeta?: string;
  comprobanteUrl?: string;
  observaciones?: string;
  nIdUsuarioRegistro?: number;
  nIdCaja?: number;
  nIdCorteCaja?: number;
  estatus?: string;
  estadoRepCanonico?: string;
  uuidRepCanonico?: string;
  nIdComplementoRepCanonico?: number;
  conciliado?: boolean;
  fechaConciliacion?: Date;
  aplicaciones?: PagoAplicacionLineaDto[];
}