import { TcCategoria } from './TcCategoria';
import { TcCategoriaGeneral } from './TcCategoriaGeneral';
import { TcGanancia } from './TcGanancia';
import { Usuarios } from '../../administracion/interfaces/usuarios';
import { TcClavesat } from './TcClavesat';
import { TcDescuento } from './TcDescuento';
import Decimal from 'decimal.js';
export class TcProducto{
nId: number;
dFecha: Date;
nEstatus: number;
nIdCategoriaGeneral:number;
nIdCategoria:number;
nPrecio: Decimal;
sDescripcion: string; 
sMarca: string;
sMoneda: string;
sNoParte: string;
sProducto :string;
nIdusuario:number;
nIdGanancia:number;
nIdclavesat:number;
tcCategoria: TcCategoria; 
tcCategoriaGeneral: TcCategoriaGeneral; 
tcGanancia: TcGanancia;
tcUsuario: Usuarios;
tcClavesat: TcClavesat;
nPrecioPeso:Decimal;
nPrecioSinIva:Decimal;
nPrecioConIva:Decimal;
sIdBar:string;
nPrecioIva:Decimal;
nIdDescuento:number;
tcDescuento:TcDescuento;
nIdMarca:number;
nPeso:Decimal;	
nLargo:Decimal;	
nAlto:Decimal;	
nAncho:Decimal;	
nVolumen:Decimal;	
sRutaImagen:String;

}