export enum TipoDoc {
    PDF_FACTURA = 'PDF_FACTURA',
    XML_FACTURA = 'XML_FACTURA',
  XML_ACUSE_CANCELACION = 'XML_ACUSE_CANCELACION',
  PDF_COMPLEMENTO_PAGO = 'PDF_COMPLEMENTO_PAGO',
  XML_COMPLEMENTO_PAGO = 'XML_COMPLEMENTO_PAGO',
  ZIP_COMPLEMENTOS_PAGO = 'ZIP_COMPLEMENTOS_PAGO',
    
  }
  